apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeshark
  namespace: argocd # Or your Argo CD namespace
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: https://helm.kubehq.com
    chart: kubeshark
    targetRevision: 52.3.78  # Update to latest version
    # Or if using Helm chart directly:
    # chart: kubeshark
    # targetRevision: HEAD
    # helm:
    #   values: |
    #     # Your Helm values here
  destination:
    name: in-cluster # Target cluster
    namespace: kubeshark # Namespace where Kubeshark will run
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true




