apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pdf
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://stirling-tools.github.io/Stirling-PDF-chart
    chart: stirling-pdf
    targetRevision: '2.2.0'
    helm:
      parameters:
        - name: installCRDs
          value: 'true'
  destination:
    namespace: pdf
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
